# Generated by Django 6.0.2 on 2026-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Andriod Phone', 'Andriod Phone'), ('iPhone', 'iPhone'), ('Printer', 'Printer')], default='Laptop', max_length=100),
        ),
    ]
