# Generated by Django 6.0.2 on 2026-02-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branchinventory_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('INSTALLMENT', 'INSTALLMENT')], max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_months', models.IntegerField()),
                ('monthly_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('change_given', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.payment')),
            ],
        ),
    ]
